spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://semapyeon.cf24ii2wemah.ap-northeast-2.rds.amazonaws.com:3306/semapyeon
    username: semapyeon
    password: semapyeon

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: semapyeonsemapyeonsemapyeonsemapyeonsemapyeonsemapyeonsemapyeon
